include ../../../Makefile

.PHONY: set-credentials
set-credentials: db_username=
set-credentials: db_password=
set-credentials:
	export TF_VAR_db_username="$(db_username)"
	export TF_VAR_db_password="$(db_password)"
